### ISSUE TITLE
Trikit error : simple lunch

### ISSUE THREAD

**Issue by CharlieL54** [trikit/trikit#1]
Hello,

I simply try to run 

_df = load("raa", tri_type="cum")
bcl = df.boot_cl(sims=1000, two_sided=False, random_state=516)_

But I have this error :

  _Cell In[5], line 2
    bcl = df.boot_cl(sims=1000, two_sided=False, random_state=516)

  File ~\AppData\Local\anaconda3\envs\Mack_MGA\lib\site-packages\trikit\triangle.py:1204 in boot_cl
    return(BootstrapChainLadder(self).__call__(**kwds))

  File ~\AppData\Local\anaconda3\envs\Mack_MGA\lib\site-packages\trikit\estimators\bootstrap.py:185 in __call__
    std_error = self._bs_std_error(dfreserves)

  File ~\AppData\Local\anaconda3\envs\Mack_MGA\lib\site-packages\trikit\estimators\bootstrap.py:736 in _bs_std_error
    return(origin_se.append(total_se))

  File ~\AppData\Local\anaconda3\envs\Mack_MGA\lib\site-packages\pandas\core\generic.py:5989 in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'append'_

**Comment by jtrive84** [comment]
Hello. That seems to be an issue with the version of Pandas. append is no longer supported for versions > 2.0. trikit has been updated to version 0.3.5 to be Pandas 2.0+ compatible. It should work without issue if you reinstall from PyPI.

**Comment by jtrive84** [comment]
This is another Pandas dependency issue. applymap has been deprecated,starting in v2.1.0. Either upgrade Pandas to be greater than 2.1, or install trikit from version 0.3.6 which pins the dependencies. Thanks for the heads-up.

**Comment by CharlieL54** [comment]
I try to update trikit but I have this error (i think there is a problem with numpy, I use numpy 1.26.2) :   

 _C:\Users\...\AppData\Local\anaconda3\lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    C:\Users\...\AppData\Local\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    [end of output]
  
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure
  
  Encountered error while trying to install package.
  
  numpy
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1_

**Comment by jtrive84** [comment]
Try creating a new virtual environment. Install trikit using pip. This will install all the required dependencies and versions.

**Comment by CharlieL54** [comment]
Same problem with a virtual environment

**Comment by CharlieL54** [comment]
What version of python are you using?
The problem with numpy, explained previously, can be solved with python 3.8 but trikit 0.3.7 doesn't work with python 3.8...
